---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.tenant.name }}-stressed
  namespace: {{ $.Values.tenant.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ $.Values.tenant.name }}-stressed
  template:
    metadata:
      labels:
        app: {{ $.Values.tenant.name }}-stressed
    spec:
      containers:
        - name: stress
          image: polinux/stress
          args:
            - "--cpu"
            - "8"
            - "--timeout"
            - "300s"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          imagePullPolicy: Always
