kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-{{ $.Values.tenant.name }}
  namespace: {{ $.Values.tenant.name }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ $.Values.tenant.name }}
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 250Mi
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 4
          periodSeconds: 15
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 120
      selectPolicy: Max
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
        - type: Percent
          value: 10
          periodSeconds: 60